import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Navgation from './components/navigation';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};


export default function RootLayout({ children }) {



  return (
    
      <html>
      <body>
        <Navgation />

        <>{children}</>
       
      </body>
    </html>
  );
}
